name: 'unity-get-version-github-action'
description: 'This action returns the version of Unity used in the specified Unity project.'
inputs:
  project-directory:
    description: >
      Open the project at the given path. If the pathname contains spaces, enclose it in quotes.
    required: true
outputs:
  version:
    description: 'Unity Version'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"